services:
  front:
    build: ../front
    networks:
    - frontend
    ports:
    - "3000:3000"
  couchdb:
    image: couchdb:2.1
    networks:
    - database
    ports:
    - "5984:5984"
  back:
    build: ../back
    networks:
    - frontend
    - database
    ports:
    - "9000:9000"

networks:
   frontend:
   database:
